table 2018
	lineageTag: 8450d17d-8e63-403f-a625-2f82d1cd96df

	measure gross_revenue = SUMX(FILTER(full_database, [is_canceled] = 0), [adr] * ([stays_in_week_nights] = [stays_in_weekend_nights]))
		lineageTag: 47845925-0c1a-4aab-bdba-9f96971a4d7c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hotel
		dataType: string
		lineageTag: f6ba1bde-e409-4b9a-8ad4-10e15d8c58e9
		summarizeBy: none
		sourceColumn: hotel

		annotation SummarizationSetBy = Automatic

	column is_canceled
		dataType: int64
		formatString: 0
		lineageTag: 4b07aaa3-b4f6-4360-821a-3f13bdf15b2c
		summarizeBy: sum
		sourceColumn: is_canceled

		annotation SummarizationSetBy = Automatic

	column lead_time
		dataType: int64
		formatString: 0
		lineageTag: 98351600-9036-44ac-b53e-80443034ac30
		summarizeBy: sum
		sourceColumn: lead_time

		annotation SummarizationSetBy = Automatic

	column arrival_date_year
		dataType: int64
		formatString: 0
		lineageTag: 68777440-b777-4962-958c-7c2ddc896e79
		summarizeBy: sum
		sourceColumn: arrival_date_year

		annotation SummarizationSetBy = Automatic

	column arrival_date_month
		dataType: string
		lineageTag: 09dabdc5-fbb4-4962-bcd6-2eb14d401dbb
		summarizeBy: none
		sourceColumn: arrival_date_month

		annotation SummarizationSetBy = Automatic

	column arrival_date_week_number
		dataType: int64
		formatString: 0
		lineageTag: 2470c486-01d9-4ee5-8ff4-fe112c353437
		summarizeBy: sum
		sourceColumn: arrival_date_week_number

		annotation SummarizationSetBy = Automatic

	column arrival_date_day_of_month
		dataType: int64
		formatString: 0
		lineageTag: 665de624-6d92-4b6d-bec0-54287565594a
		summarizeBy: sum
		sourceColumn: arrival_date_day_of_month

		annotation SummarizationSetBy = Automatic

	column stays_in_weekend_nights
		dataType: int64
		formatString: 0
		lineageTag: 654dc065-697e-46d4-9e3f-27ac21c394df
		summarizeBy: sum
		sourceColumn: stays_in_weekend_nights

		annotation SummarizationSetBy = Automatic

	column stays_in_week_nights
		dataType: int64
		formatString: 0
		lineageTag: 1a7383bd-0424-4221-b425-6eb0c7a4926d
		summarizeBy: sum
		sourceColumn: stays_in_week_nights

		annotation SummarizationSetBy = Automatic

	column adults
		dataType: int64
		formatString: 0
		lineageTag: 8cb150ae-6fe5-467c-8850-f5fb8d503443
		summarizeBy: sum
		sourceColumn: adults

		annotation SummarizationSetBy = Automatic

	column children
		dataType: int64
		formatString: 0
		lineageTag: dc67ce85-d85a-441f-82d1-025ebab4b32f
		summarizeBy: sum
		sourceColumn: children

		annotation SummarizationSetBy = Automatic

	column babies
		dataType: int64
		formatString: 0
		lineageTag: b35cfffb-fe88-446f-b39f-df36add41ad4
		summarizeBy: sum
		sourceColumn: babies

		annotation SummarizationSetBy = Automatic

	column meal
		dataType: string
		lineageTag: d4a831f4-f6fd-4e9a-858c-eba2f894a8f4
		summarizeBy: none
		sourceColumn: meal

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 456cf4c8-f1bc-4b76-8db1-1ca386871f6f
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column market_segment
		dataType: string
		lineageTag: adbe6d66-53c4-45b6-83f7-d2cf77300fec
		summarizeBy: none
		sourceColumn: market_segment

		annotation SummarizationSetBy = Automatic

	column distribution_channel
		dataType: string
		lineageTag: df9c4155-4bf8-4d0a-961d-001c05e09b92
		summarizeBy: none
		sourceColumn: distribution_channel

		annotation SummarizationSetBy = Automatic

	column is_repeated_guest
		dataType: int64
		formatString: 0
		lineageTag: 53e5b055-d604-497b-a74f-d0792f4cfd0b
		summarizeBy: sum
		sourceColumn: is_repeated_guest

		annotation SummarizationSetBy = Automatic

	column previous_cancellations
		dataType: int64
		formatString: 0
		lineageTag: 7cb111a3-c6d2-4f97-8aa6-99156334de8d
		summarizeBy: sum
		sourceColumn: previous_cancellations

		annotation SummarizationSetBy = Automatic

	column previous_bookings_not_canceled
		dataType: int64
		formatString: 0
		lineageTag: 474335a3-6ef3-484e-9880-cb325bf419af
		summarizeBy: sum
		sourceColumn: previous_bookings_not_canceled

		annotation SummarizationSetBy = Automatic

	column reserved_room_type
		dataType: string
		lineageTag: 199d7974-bf51-4a22-adba-bd806af5f8aa
		summarizeBy: none
		sourceColumn: reserved_room_type

		annotation SummarizationSetBy = Automatic

	column assigned_room_type
		dataType: string
		lineageTag: 0802e969-c322-407c-9e4c-8993539fd2cb
		summarizeBy: none
		sourceColumn: assigned_room_type

		annotation SummarizationSetBy = Automatic

	column booking_changes
		dataType: int64
		formatString: 0
		lineageTag: c676ed5e-4883-4a49-8e7a-764e5fd3e762
		summarizeBy: sum
		sourceColumn: booking_changes

		annotation SummarizationSetBy = Automatic

	column deposit_type
		dataType: string
		lineageTag: 39a796f9-932a-448f-948f-41d158b7537d
		summarizeBy: none
		sourceColumn: deposit_type

		annotation SummarizationSetBy = Automatic

	column agent
		dataType: string
		lineageTag: 10427881-0fe0-4727-9d17-f60e82a95a6e
		summarizeBy: none
		sourceColumn: agent

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: b30c00db-4ccf-46ca-a4f7-d2744adb3cc8
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column days_in_waiting_list
		dataType: int64
		formatString: 0
		lineageTag: a8b2bde0-39ce-45d6-84ca-86907edf1076
		summarizeBy: sum
		sourceColumn: days_in_waiting_list

		annotation SummarizationSetBy = Automatic

	column customer_type
		dataType: string
		lineageTag: 7fb73971-7e17-496d-a4a2-e19f6ced420f
		summarizeBy: none
		sourceColumn: customer_type

		annotation SummarizationSetBy = Automatic

	column adr
		dataType: double
		lineageTag: 57f6cae5-ac19-4b45-828e-e8fe765abae9
		summarizeBy: sum
		sourceColumn: adr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column required_car_parking_spaces
		dataType: int64
		formatString: 0
		lineageTag: 359cd6fb-c79a-47ad-9f04-e5167a371002
		summarizeBy: sum
		sourceColumn: required_car_parking_spaces

		annotation SummarizationSetBy = Automatic

	column total_of_special_requests
		dataType: int64
		formatString: 0
		lineageTag: 982eed7a-79a6-4749-8e9c-0c4d30bcaf51
		summarizeBy: sum
		sourceColumn: total_of_special_requests

		annotation SummarizationSetBy = Automatic

	column reservation_status
		dataType: string
		lineageTag: db3f9866-96c9-438b-8d1b-9dc9985888d3
		summarizeBy: none
		sourceColumn: reservation_status

		annotation SummarizationSetBy = Automatic

	column reservation_status_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 17ec8a7d-bec2-4924-9784-83829e08b021
		summarizeBy: none
		sourceColumn: reservation_status_date

		variation Variation
			isDefault
			relationship: 28cd1d7b-4853-4be0-9f69-f37535759648
			defaultHierarchy: LocalDateTable_cd7610f8-49bf-46ca-bbb7-d31ec0b129b0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 2018 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://absentdata.com/wp-content/uploads/2021/05/hotel_revenue_historical_full-2.xlsx"), null, true),
				    #"2018_Sheet" = Source{[Item="2018",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"2018_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"hotel", type text}, {"is_canceled", Int64.Type}, {"lead_time", Int64.Type}, {"arrival_date_year", Int64.Type}, {"arrival_date_month", type text}, {"arrival_date_week_number", Int64.Type}, {"arrival_date_day_of_month", Int64.Type}, {"stays_in_weekend_nights", Int64.Type}, {"stays_in_week_nights", Int64.Type}, {"adults", Int64.Type}, {"children", Int64.Type}, {"babies", Int64.Type}, {"meal", type text}, {"country", type text}, {"market_segment", type text}, {"distribution_channel", type text}, {"is_repeated_guest", Int64.Type}, {"previous_cancellations", Int64.Type}, {"previous_bookings_not_canceled", Int64.Type}, {"reserved_room_type", type text}, {"assigned_room_type", type text}, {"booking_changes", Int64.Type}, {"deposit_type", type text}, {"agent", type any}, {"company", type any}, {"days_in_waiting_list", Int64.Type}, {"customer_type", type text}, {"adr", type number}, {"required_car_parking_spaces", Int64.Type}, {"total_of_special_requests", Int64.Type}, {"reservation_status", type text}, {"reservation_status_date", type date}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type")
				in
				    #"Removed Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

