table full_database
	lineageTag: ccb24068-d023-42d1-ba33-7bbfad60d636

	measure 'total reservations' = COUNTROWS('full_database')
		formatString: 0
		lineageTag: ccbd98fe-265a-4645-97f4-502754c9d19c

	measure 'confirmed reservations' = CALCULATE(COUNTROWS('full_database'), 'full_database'[is_canceled] = 0)
		formatString: 0
		lineageTag: 8133e52a-02dd-4de0-a0dc-d0e9516c4f84

	measure 'canceled reservations' = CALCULATE(COUNTROWS('full_database'), 'full_database'[is_canceled] = 1)
		formatString: 0
		lineageTag: d5c23216-67ca-4435-bc7e-2630ee9940ec

	measure 'churn rate' = DIVIDE([canceled reservations], [total reservations], 0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: fdcbe734-f1c1-4e0b-b92b-f146afd19a39

	measure 'total nights' = CALCULATE(SUMX('full_database', [stays_in_week_nights] + [stays_in_weekend_nights]), 'full_database'[is_canceled] = 0)
		formatString: 0
		lineageTag: cd9f0c1f-7ca0-45d4-b52a-7a13db079e3f

	measure 'average nights per reserve' = DIVIDE([total nights], [confirmed reservations], 0)
		lineageTag: 826c5ece-c4d9-44fb-bdd6-da66dee54547

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'weekend nights' = CALCULATE(SUM('full_database'[stays_in_weekend_nights]), 'full_database'[is_canceled] = 0)
		formatString: 0
		lineageTag: b6567adf-604c-4898-aca4-8119c5bed0a2

	measure 'week nights' = CALCULATE(SUM('full_database'[stays_in_week_nights]), 'full_database'[is_canceled] = 0)
		formatString: 0
		lineageTag: 46fdb686-737d-48a5-8921-526ed892bba5

	measure 'percentage of weekend nights' = DIVIDE([weekend nights], [total nights], 0) * 100
		lineageTag: 45aad8f4-e2fc-4209-ab8f-9832f56ac4c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'gross revenue' = SUMX(FILTER('full_database', 'full_database'[is_canceled] = 0), 'full_database'[adr] * ('full_database'[stays_in_week_nights] + 'full_database'[stays_in_weekend_nights]))
		lineageTag: f700fe0e-611e-4d78-a548-f1d9334c3a64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'potencial revenue' = SUMX('full_database', 'full_database'[adr] * ('full_database'[stays_in_week_nights] + 'full_database'[stays_in_weekend_nights]))
		lineageTag: 3be97b59-71d5-4b45-94db-3a57605c3c60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'lost revenue' = SUMX(FILTER('full_database', 'full_database'[is_canceled] = 1), 'full_database'[adr] * ('full_database'[stays_in_week_nights] + 'full_database'[stays_in_weekend_nights]) * (1 - 'full_database'[discount]))
		lineageTag: 3ab47373-2bf3-4085-bfef-0303fdd37058

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average adr' = CALCULATE(AVERAGE('full_database'[adr]), 'full_database'[is_canceled] = 0)
		lineageTag: b032e1c5-e6f5-4536-8647-205d41d98173

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'total discounts' = SUMX(FILTER('full_database', 'full_database'[is_canceled] = 0), [gross revenue] * 'full_database'[discount])
		lineageTag: 484457cc-9007-4a22-9e60-1d6896043ce7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average percentage of discount' = CALCULATE(AVERAGE('full_database'[discount]), 'full_database'[is_canceled] = 0) * 100
		lineageTag: 31b22c91-3c8d-4404-915a-144957bafb1f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'revenue post discount' = [gross revenue] - [total discounts]
		lineageTag: e0c84e8b-0945-46e1-9b95-e1874de1fef3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meal costs' = SUMX(FILTER('full_database', 'full_database'[is_canceled]), 'full_database'[meal_cost] * ('full_database'[stays_in_week_nights] + 'full_database'[stays_in_weekend_nights]))
		lineageTag: 868d9236-2cea-4bb9-84eb-084ab33b62e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average meal cost per night' = CALCULATE(AVERAGE('full_database'[meal_cost]), 'full_database'[is_canceled] = 0)
		lineageTag: 2e5546ea-efbf-4631-931c-d21bdab57d3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average cost per reserve' = DIVIDE([meal costs], [confirmed reservations], 0)
		lineageTag: 1a04f93c-a7ff-4e35-86f9-5f7560d4e536

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'net revenue' = [gross revenue] - [total discounts] - [meal costs]
		lineageTag: 87be6db1-1ab3-4794-a5ae-f138c9eb9720

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'net margin' = ```
			DIVIDE([net revenue], [gross revenue], 0) 
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 48425480-98f6-45a5-b1e3-fabb1f45cda1

	measure 'net revenue per reserve' = DIVIDE([net revenue], [confirmed reservations], 0)
		lineageTag: 4e6bf9ac-0e42-4991-86ec-2d6a00ae3b08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ner revenue per night' = DIVIDE([net revenue], [total nights], 0)
		lineageTag: 9624f82a-d775-4c4f-b629-3acce95bff7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cancelations impact' = DIVIDE([lost revenue], [potencial revenue], 0) * 100
		lineageTag: e47c5ee1-aedd-4eca-b793-c0160bc8d26c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ratio lost vs real' = DIVIDE([lost revenue], [net revenue], 0) * 100
		lineageTag: bdb406e8-a94f-4823-a85d-9d3c58f66410

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'total guests' = CALCULATE(SUMX('full_database', 'full_database'[adults] + 'full_database'[children] + 'full_database'[babies]), 'full_database'[is_canceled] = 0)
		formatString: 0
		lineageTag: 3baebd39-0eff-46c8-901e-c51766d6517a

	measure 'net revenue per guest' = DIVIDE([net revenue], [total guests], 0)
		lineageTag: 0f38b507-726b-4ef8-85b5-6394892f0f29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'percentage repeated guest' = DIVIDE(CALCULATE(COUNTROWS('full_database'), 'full_database'[is_repeated_guest] = 1, 'full_database'[is_canceled] = 0), [confirmed reservations], 0) * 100
		lineageTag: cb56177c-29fd-4a72-9625-97d460b1e639

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average lead time' = CALCULATE(AVERAGE('full_database'[lead_time]), 'full_database'[is_canceled] = 0)
		lineageTag: d4b409bd-78e1-4119-8087-b49ab1abc8cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'past year net revenue' = CALCULATE([net revenue], DATEADD('full_database'[reservation_status_date], -1, YEAR))
		lineageTag: 7a2882b6-0f2d-484b-8614-5194476d77f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'grow YoY' = DIVIDE([net revenue] - [past year net revenue], [past year net revenue], 0) * 100
		lineageTag: f4e73c3d-5710-406a-b340-05932c174b48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'past month net revenue' = CALCULATE([net revenue], DATEADD('full_database'[reservation_status_date], -1, MONTH))
		lineageTag: 9891e9bc-cb84-440b-9d50-6863d9cae64c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'grow MoM' = DIVIDE([net revenue] - [past month net revenue], [past month net revenue], 0) * 100
		lineageTag: b56d199d-f3ca-468f-992c-682babb415f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hotel
		dataType: string
		lineageTag: 6b734fd9-eb28-4a51-a87f-77ea82bbf3b2
		summarizeBy: none
		sourceColumn: hotel

		annotation SummarizationSetBy = Automatic

	column is_canceled
		dataType: int64
		formatString: 0
		lineageTag: a389ea95-5147-4374-82af-1e5fcd1cb34f
		summarizeBy: sum
		sourceColumn: is_canceled

		annotation SummarizationSetBy = Automatic

	column lead_time
		dataType: int64
		formatString: 0
		lineageTag: 4d45bf4f-222d-4f2c-a471-afc69a1cb76a
		summarizeBy: sum
		sourceColumn: lead_time

		annotation SummarizationSetBy = Automatic

	column arrival_date_year
		dataType: string
		lineageTag: 29dcf6de-9ffa-4301-acaa-5dd3fc24c45a
		summarizeBy: none
		sourceColumn: arrival_date_year

		annotation SummarizationSetBy = Automatic

	column arrival_date_month
		dataType: string
		lineageTag: 306bfd16-5edc-4c17-bec8-231637b2f07b
		summarizeBy: none
		sourceColumn: arrival_date_month

		annotation SummarizationSetBy = Automatic

	column arrival_date_week_number
		dataType: int64
		formatString: 0
		lineageTag: 0ef35db9-edef-4e3a-a676-9d6bc78d233c
		summarizeBy: sum
		sourceColumn: arrival_date_week_number

		annotation SummarizationSetBy = Automatic

	column arrival_date_day_of_month
		dataType: int64
		formatString: 0
		lineageTag: c256c4e9-16e9-4a48-871a-fe2ad660a3f6
		summarizeBy: sum
		sourceColumn: arrival_date_day_of_month

		annotation SummarizationSetBy = Automatic

	column stays_in_weekend_nights
		dataType: int64
		formatString: 0
		lineageTag: 4a4b367c-fdae-421c-bb28-7ec0683ce7c0
		summarizeBy: sum
		sourceColumn: stays_in_weekend_nights

		annotation SummarizationSetBy = Automatic

	column stays_in_week_nights
		dataType: int64
		formatString: 0
		lineageTag: 0714639b-3a32-466e-b888-612db6fc5e72
		summarizeBy: sum
		sourceColumn: stays_in_week_nights

		annotation SummarizationSetBy = Automatic

	column adults
		dataType: int64
		formatString: 0
		lineageTag: ebbd8018-4558-4372-90d8-6909928ccc3b
		summarizeBy: sum
		sourceColumn: adults

		annotation SummarizationSetBy = Automatic

	column children
		dataType: int64
		formatString: 0
		lineageTag: a846e293-4d39-49aa-b883-d04b23f53150
		summarizeBy: sum
		sourceColumn: children

		annotation SummarizationSetBy = Automatic

	column babies
		dataType: int64
		formatString: 0
		lineageTag: 6ddcf1b3-3817-490c-afdb-cc6f17657774
		summarizeBy: sum
		sourceColumn: babies

		annotation SummarizationSetBy = Automatic

	column meal
		dataType: string
		lineageTag: cfcb8daa-3c91-4d1d-9f2d-38b4b06dd4b0
		summarizeBy: none
		sourceColumn: meal

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 869a6989-bddf-40bb-a2a8-0c9055aa3d1e
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column market_segment
		dataType: string
		lineageTag: f58c4aa5-5fc1-4ffc-a338-8549072701e9
		summarizeBy: none
		sourceColumn: market_segment

		annotation SummarizationSetBy = Automatic

	column distribution_channel
		dataType: string
		lineageTag: fce20081-2404-4670-afa2-223462368a6a
		summarizeBy: none
		sourceColumn: distribution_channel

		annotation SummarizationSetBy = Automatic

	column is_repeated_guest
		dataType: int64
		formatString: 0
		lineageTag: 4d0ed3eb-8371-4019-975e-faa4b3028277
		summarizeBy: sum
		sourceColumn: is_repeated_guest

		annotation SummarizationSetBy = Automatic

	column previous_cancellations
		dataType: int64
		formatString: 0
		lineageTag: 78a56860-deeb-41e1-8877-69770760be2f
		summarizeBy: sum
		sourceColumn: previous_cancellations

		annotation SummarizationSetBy = Automatic

	column previous_bookings_not_canceled
		dataType: int64
		formatString: 0
		lineageTag: 57b9c555-381d-421b-b9bc-a3af61a9b937
		summarizeBy: sum
		sourceColumn: previous_bookings_not_canceled

		annotation SummarizationSetBy = Automatic

	column reserved_room_type
		dataType: string
		lineageTag: 41c8e3e7-6b93-4a03-8f36-d23ba73900ea
		summarizeBy: none
		sourceColumn: reserved_room_type

		annotation SummarizationSetBy = Automatic

	column assigned_room_type
		dataType: string
		lineageTag: b3be7983-c698-4da4-ac98-25f81e7e85af
		summarizeBy: none
		sourceColumn: assigned_room_type

		annotation SummarizationSetBy = Automatic

	column booking_changes
		dataType: int64
		formatString: 0
		lineageTag: ed603a65-e04d-4fc4-9c24-0c3d351b4aa8
		summarizeBy: sum
		sourceColumn: booking_changes

		annotation SummarizationSetBy = Automatic

	column deposit_type
		dataType: string
		lineageTag: 0ef09142-c5e0-45f4-82ae-38a611c4c0c7
		summarizeBy: none
		sourceColumn: deposit_type

		annotation SummarizationSetBy = Automatic

	column agent
		dataType: string
		lineageTag: 1247c5c0-9026-4648-bfe7-ea8f981f427e
		summarizeBy: none
		sourceColumn: agent

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 08fb1c03-2d82-4c0b-928a-bcc312caf513
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column days_in_waiting_list
		dataType: int64
		formatString: 0
		lineageTag: 5f3f3dfb-6231-4ba8-9ff0-f6ba4eaaa2f8
		summarizeBy: sum
		sourceColumn: days_in_waiting_list

		annotation SummarizationSetBy = Automatic

	column customer_type
		dataType: string
		lineageTag: a4020ba4-7dae-46fb-9eef-a0eb81e145a7
		summarizeBy: none
		sourceColumn: customer_type

		annotation SummarizationSetBy = Automatic

	column adr
		dataType: double
		lineageTag: 02c7b7e8-6d31-44cc-baef-9e4266b134e7
		summarizeBy: sum
		sourceColumn: adr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column required_car_parking_spaces
		dataType: int64
		formatString: 0
		lineageTag: 39569c1d-1ded-407c-ba29-af7db6df759b
		summarizeBy: sum
		sourceColumn: required_car_parking_spaces

		annotation SummarizationSetBy = Automatic

	column total_of_special_requests
		dataType: int64
		formatString: 0
		lineageTag: 0984a4d5-6bd1-4ee7-affd-f8aa5197b6eb
		summarizeBy: sum
		sourceColumn: total_of_special_requests

		annotation SummarizationSetBy = Automatic

	column reservation_status
		dataType: string
		lineageTag: 211a0b9d-f2ce-45a8-9725-eb5b4ac397a4
		summarizeBy: none
		sourceColumn: reservation_status

		annotation SummarizationSetBy = Automatic

	column reservation_status_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: a83a6b08-806f-49ec-b275-09da6eecad74
		summarizeBy: none
		sourceColumn: reservation_status_date

		variation Variation
			isDefault
			relationship: 933b3d44-d984-40d9-8d30-4385216ddd47
			defaultHierarchy: LocalDateTable_ac91903e-cb66-4401-9a23-d6af2d23b515.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column discount
		dataType: double
		lineageTag: d1ecf296-0418-4d1a-8521-1e4ba86a800c
		summarizeBy: sum
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column meal_cost
		dataType: double
		lineageTag: 62130722-bbbc-45b2-8b43-567a0fbcfb24
		summarizeBy: sum
		sourceColumn: meal_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition full_database = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"2018", #"2019", #"2020"}),
				    #"Merged Queries" = Table.NestedJoin(Source, {"market_segment"}, market_segment, {"market_segment"}, "market_segment.1", JoinKind.LeftOuter),
				    #"Expanded market_segment.1" = Table.ExpandTableColumn(#"Merged Queries", "market_segment.1", {"Discount"}, {"market_segment.1.Discount"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded market_segment.1",{{"market_segment.1.Discount", "discount"}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns", {"meal"}, meal_cost, {"meal"}, "meal_cost", JoinKind.LeftOuter),
				    #"Expanded meal_cost" = Table.ExpandTableColumn(#"Merged Queries1", "meal_cost", {"Cost"}, {"meal_cost.Cost"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded meal_cost",{{"meal_cost.Cost", "meal_cost"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns1", each [reservation_status_date] > #date(2017, 12, 31)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows1",{{"arrival_date_year", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

