table meal_cost
	lineageTag: 9921694d-beb2-46d9-ab67-2cc9430b9d2d

	column Cost
		dataType: double
		lineageTag: 0f10d6d2-70a1-4139-bd99-2d8d8fbc22ce
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column meal
		dataType: string
		lineageTag: e899b058-e502-4283-88e5-02c87814d82c
		summarizeBy: none
		sourceColumn: meal

		annotation SummarizationSetBy = Automatic

	partition meal_cost = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://absentdata.com/wp-content/uploads/2021/05/hotel_revenue_historical_full-2.xlsx"), null, true),
				    meal_cost_Sheet = Source{[Item="meal_cost",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(meal_cost_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Cost", type number}, {"meal", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

